# Generated by Django 6.0.5 on 2026-05-06 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('priority', models.CharField(choices=[('High', 'Высокий'), ('Medium', 'Средний'), ('Low', 'Низкий')], default='Medium', max_length=10)),
                ('status', models.CharField(choices=[('todo', 'К выполнению'), ('progress', 'В работе'), ('review', 'На проверке'), ('done', 'Готово')], default='todo', max_length=10)),
                ('deadline', models.DateField(blank=True, null=True)),
            ],
        ),
    ]
